version: '3.8'

services:
  mongodb:
    image: mongo:latest 
    container_name: product_mongodb
    ports:
      - "27018:27017"
    volumes:
      - product_mongodb_data:/data/db
    restart: always 
    networks:
      - lyxa_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: product_rabbitmq
    ports:
      - "5673:5672" # AMQP protocol port
      - "15673:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: always
    networks:
      - lyxa_network

  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product_service
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      MONGODB_URI: mongodb://mongodb:27017/auth_service
      RABBITMQ_URI: amqp://user:password@rabbitmq:5672
      AUTH_SERVICE_QUEUE: auth_queue
    depends_on:
      - mongodb 
      - rabbitmq 
    restart: always
    networks:
      - lyxa_network

networks:
  lyxa_network:
    driver: bridge

volumes:
  product_mongodb_data:
