version: '3.8'

services:
  mongodb:
    image: mongo:latest 
    container_name: auth_mongodb
    ports:
      - "27018:27018"
    volumes:
      - mongodb_data:/data/db
    restart: always 

  rabbitmq:
    image: rabbitmq:3-management-alpine # Use RabbitMQ with management plugin
    container_name: auth_rabbitmq
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: always

  auth-service:
    build:
      context: . # Build from the current directory (where Dockerfile is located)
      dockerfile: Dockerfile
    container_name: auth_service
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      MONGODB_URI: mongodb://mongodb:27017/auth_service
      RABBITMQ_URI: amqp://rabbitmq:5672
      JWT_SECRET: supersecretjwtkey 
      JWT_ACCESS_TOKEN_EXPIRATION_TIME: 3600
      JWT_REFRESH_TOKEN_EXPIRATION_TIME: 604800
    depends_on:
      - mongodb 
      - rabbitmq 
    restart: always

volumes:
  mongodb_data:
